version: '3.1'
services:
  autoware_mini:
    stdin_open: true
    command: /bin/bash
    build:
      context: ${PWD}/autoware_mini
      dockerfile: Dockerfile
      args: 
          - PROCESS_COUNT=${PROCESS_COUNT}
          - DISPLAY=$DISPLAY
          - QT_X11_NO_MITSHM=1
          - NVIDIA_DRIVER_CAPABILITIES=all
          - XAUTHORITY=/tmp/.docker.xauth
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ~/.Xauthority:/root/.Xauthority
    image: "prathap/autoware_mini:v0.1"
    container_name: autoware_mini 
    network_mode: "host"
